name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        run: |
          export SSHPASS='${{ secrets.SSH_PASSWORD }}'
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            set -e  # Exit on error
            
            echo "Setting up environment..."
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            export PATH="/home/playtime/.nvm/versions/node/v23.2.0/bin:$PATH"
            
            echo "Verifying commands..."
            which npm
            which pm2
            
            echo "Navigating to project..."
            cd ~/playtime
            
            echo "Updating from git..."
            git fetch origin main
            git reset --hard origin/main
            
            echo "Installing dependencies..."
            /home/playtime/.nvm/versions/node/v23.2.0/bin/npm ci --no-audit --no-fund
            
            echo "Managing process..."
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            
            echo "Starting new process..."
            /home/playtime/.nvm/versions/node/v23.2.0/bin/pm2 delete telegram || true
            /home/playtime/.nvm/versions/node/v23.2.0/bin/pm2 start playtime/telegram.js --name telegram
            
            echo "Deployment complete!"
            exit 0
          '
