name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug SSH Connection
        run: |
          echo "Attempting to connect to ${{ secrets.SSH_HOST }}"
          echo "With username: ${{ secrets.SSH_USERNAME }}"
          
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          debug: true  # Added debug mode
          script: |
            whoami
            pwd
            cd playtime
            git fetch origin main
            git reset --hard origin/main
            npm ci
            guix package -m manifest.scm
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
            
            # Start the Node.js process with PM2
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
