name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Debug Secrets
        run: |
          if [ ! -z "${{ secrets.SSH_USERNAME }}" ]; then
            echo "Username is set (length: $(echo -n "${{ secrets.SSH_USERNAME }}" | wc -c))"
          fi
          
      - name: Deploy using SSH
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          command: |
            whoami
            pwd
            cd playtime
            git fetch origin main
            git reset --hard origin/main
            npm ci
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
