name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        run: |
          export SSHPASS='${{ secrets.SSH_PASSWORD }}'
          sshpass -e ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USERNAME }}@${{ secrets.SSH_HOST }} '
            # Source profile to get environment variables
            source ~/.profile
            source ~/.bashrc
            
            # Navigate to project
            cd playtime
            
            # Git operations
            git fetch origin main
            git reset --hard origin/main
            
            # Ensure npm is available
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            
            # Install dependencies
            npm ci
            
            # Install pm2 globally if not present
            if ! command -v pm2 &> /dev/null; then
              npm install -g pm2
            fi
            
            # Kill existing process
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            
            # Start new process
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
          '
