name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using SSH
        uses: nekiro/ssh-job@main
        with:
          host: ${{ secrets.SSH_HOST }}
          user: ${{ secrets.SSH_USERNAME }}  # Note: changed from 'username' to 'user'
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          envs: ${{ toJson(secrets) }}  # This will pass all secrets to the shell
          command: |
            whoami
            pwd
            cd playtime
            git fetch origin main
            git reset --hard origin/main
            npm ci
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
