name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Create SSH key file
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keygen -p -m PEM -f ~/.ssh/deploy_key  # Convert to PEM format if needed
          
      - name: Deploy using SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key_path: ~/.ssh/deploy_key
          password: ${{ secrets.SSH_PASSWORD }}
          debug: true
          script: |
            whoami
            pwd
            cd playtime
            git fetch origin main
            git reset --hard origin/main
            npm ci
            pkill -f "node playtime/telegram.js" || true
            sleep 2
            pm2 delete telegram || true
            pm2 start playtime/telegram.js --name telegram
